### ISSUE TITLE
Write a KafkaTopic generator kustomize plugin

### ISSUE THREAD

**Issue by HumairAK** [operate-first/continuous-deployment#10]
Write a kustomize plugin  `kafkatopicgenerator`: 

When given an input like: 

```
apiVersion: operatefirst/v1
kind: KafkaTopicGenerator
metadata:
  name: kafka-topics
  namespace: mynamespace
clusterName: dev
defaults:
   partitions: 2
   replicas: 3
topics:
  - topicName: exampletopicA
    partitions: 4
    config: 
       retention.bytes: 853333300
       retention.ms: 172800000
  - topicName: exampletopicB
```

Should generate kafka topic manifest: 

```
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: exampletopicA
  namespace: mynamespace
  labels:
    strimzi.io/cluster: dev
    template: kafka-topics-template
spec:
    partitions: 4
    replicas: 3
    topicName: exampletopicA
    config:
       retention.bytes: 853333300
       retention.ms: 172800000
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: exampletopicB
  namespace: mynamespace
  labels:
    strimzi.io/cluster: dev
    template: kafka-topics-template
spec:
    partitions: 2
    replicas: 3
    topicName: exampletopicB
```

The plugin should be added within the operate-first/cd/kustomizePlugins/v1/kafkatopicgenerator 
Include a readme.md in this folder on the example use case like the one above, and installation instructions.
