### ISSUE TITLE
Document/Automate copying categorical data analysis sample data set to ODH attached storage

### ISSUE THREAD

**Issue by durandom** [operate-first/continuous-deployment#28]

**Comment by tumido** [comment]
@durandom  can you please point me to any ceph mini reference in ODH? I can't find any... Otherwise we can prototype this with MinIO server instance (operator based, easy, plenty of docsand examples, including an in-house from @anishasthana https://github.com/anishasthana/odh-ml-pipelines ), however that still requires persistent storage unfortunately...

If that's not possible at this moment we can try default to some external s3 store for the time being, like a public AWS/GCS bucket (so it's accessible from outside of the RH network)...

**Comment by durandom** [comment]
It's actually [ceph-nano](https://github.com/ceph/cn) and it was used in https://gitlab.com/opendatahub/jupyterhub-ansible/-/blob/master/tasks/main.yml 

@vpavlin @LaVLaS do we still do this? Do we have an alternative in ODH if ceph is not available?

@tumido or just go with the minio stuff or if you have a S3 bucket in AWS available. Whatever is quickest.

**Comment by tumido** [comment]
I'll try ceph nano then. It seems it's not dependent on persistent storage, so it should be a nice sandbox.

**Comment by durandom** [comment]
@vpavlin is there a plan in ODH to have a object storage component like ceph-nano or minio for demo purposes?

**Comment by vpavlin** [comment]
Yes, @LaVLaS is working on it - https://github.com/opendatahub-io/odh-manifests/issues/149

**Comment by tumido** [comment]
Once we have any storage available, it's only a matter of submitting Argo workflow/running as a job or even an init container..

It can look like this or similar
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: download-data-
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: source-url
        value: https://raw.githubusercontent.com/aicoe-aiops/categorical-encoding/master/notebooks/data/employee.csv
      - name: s3-key
        value: a/b/c/employee.csv
      - name: s3-bucket
        value: bucket

  templates:
    - name: main
      container:
        image: minio/mc
        command: ["/bin/sh", "-ce"]
        args:
          - |
            mc --config-dir /tmp/mc config host add s3 $HOST $ACCESS_KEY_ID $SECRET_ACCESS_KEY;
            curl {{workflow.parameters.source-url}} | mc --config-dir /tmp/mc pipe s3/{{workflow.parameters.s3-bucket}}/{{workflow.parameters.s3-key}};
        env:
          - name: HOST
            valueFrom:
              secretKeyRef:
                key: host
                name: s3-secret
          - name: ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: accessKey
                name: s3-secret
          - name: SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: secretKey
                name: s3-secret
```

basically it's just a fancy wrapper around a `curl REMOTE_URL | mc pipe S3_URI`  command
